sudo: required
language: generic
services:
  -docker

before_install:
  - docker build -t pdhakal/react-test -f ./client/dockerfile.dev ./client

script:
  - docker run -e CI=true pdhakal/react-test npm test

after_success:
  - docker build -t pdhakal/multi-client ./client
  - docker build -t pdhakal/multi-nginx ./nginx
  - docker build -t pdhakal/multi-server ./server
  - docker build -t pdhakal/multi-worker ./worker

  #log in to the docker CLI 
  - echo"$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password--stdin
  
  #take those image and push it to the docker hub .
  - docker push pdhakal/multi-client
  - docker push pdhakal/multi-nginx
  - docker push pdhakal/multi-server
  - docker push pdhakal/multi-worker
