sudo: required
language: generic
services:
  -docker

before_install:
  - docker build -t pradeep/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pradeep/react-test npm test

after_success:
  - docker build -t pdhakal/multi-client ./client
  - docker build -t pdhakal/multi-nginx ./nginx
  - docker build -t pdhakal/multi-server ./server
  - docker build -t pdhakal/multi-worker ./worker

  #log in to the docker CLI 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  #take those image and push it to the docker hub .
  - docker push pdhakal/multi-client
  - docker push pdhakal/multi-nginx
  - docker push pdhakal/multi-server
  - docker push pdhakal/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-997872640825
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
